name: Visualize Repository

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout
      
    - name: Visualize Repository
      uses: githubocto/repo-visualizer
      with:
        # Specify the output format (e.g., svg, png, dot)
        format: svg
