name: Visualize Repository

on:
  push:
    branches:
      - main

jobs:
  visualize:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Visualize Repository
      uses: githubocto/repo-visualizer@0.7.1
      
    - name: Save Visualization
      uses: actions/github-script@v4
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const svgContent = process.env.REPO_VISUALIZER_OUTPUT;
          fs.writeFileSync(path.join(process.env.GITHUB_WORKSPACE, 'diagram.svg'), svgContent);
